export const ANIMATION_DURATION_VERY_SHORT = 120;
export const ANIMATION_DURATION_SHORT = 200;
export const ANIMATION_DURATION_MEDIUM = 400;
export const ANIMATION_DURATION_LONG = 600;
export const ANIMATION_DURATION_VERY_LONG = 800;
